export const DUMMY_POSTS = [
  {
    title: "Post title",
    date: Date.now(),
    excerpt: "The post excerpt",
    imgPath:
      "https://images.nappy.co/uploads/large/21592178174kqah8td9ipie9jypo1keymszjbhqpzk0riykxxiwbcjmt6z895otlvsxe00ymauvqdxie4admvrkzwkbidhouo8xihixud4zjink.jpg?auto=format&fm=jpg&w=1280&q=75",
    altText: "hand holding a megaphone",
    slug: "test-post",
  },
  {
    title: "Post title",
    date: Date.now(),
    excerpt: "The post excerpt",
    imgPath:
      "https://images.nappy.co/uploads/large/21592178174kqah8td9ipie9jypo1keymszjbhqpzk0riykxxiwbcjmt6z895otlvsxe00ymauvqdxie4admvrkzwkbidhouo8xihixud4zjink.jpg?auto=format&fm=jpg&w=1280&q=75",
    altText: "hand holding a megaphone",
    slug: "test-post1",
  },
  {
    title: "Post title",
    date: Date.now(),
    excerpt: "The post excerpt",
    imgPath:
      "https://images.nappy.co/uploads/large/21592178174kqah8td9ipie9jypo1keymszjbhqpzk0riykxxiwbcjmt6z895otlvsxe00ymauvqdxie4admvrkzwkbidhouo8xihixud4zjink.jpg?auto=format&fm=jpg&w=1280&q=75",
    altText: "hand holding a megaphone",
    slug: "test-post2",
  },
  {
    title: "Post title",
    date: Date.now(),
    excerpt: "The post excerpt",
    imgPath:
      "https://images.nappy.co/uploads/large/21592178174kqah8td9ipie9jypo1keymszjbhqpzk0riykxxiwbcjmt6z895otlvsxe00ymauvqdxie4admvrkzwkbidhouo8xihixud4zjink.jpg?auto=format&fm=jpg&w=1280&q=75",
    altText: "hand holding a megaphone",
    slug: "test-post3",
  },
  {
    title: "Post title",
    date: Date.now(),
    excerpt: "The post excerpt",
    imgPath:
      "https://images.nappy.co/uploads/large/21592178174kqah8td9ipie9jypo1keymszjbhqpzk0riykxxiwbcjmt6z895otlvsxe00ymauvqdxie4admvrkzwkbidhouo8xihixud4zjink.jpg?auto=format&fm=jpg&w=1280&q=75",
    altText: "hand holding a megaphone",
    slug: "test-post4",
  },
  {
    title: "Post title",
    date: Date.now(),
    excerpt: "The post excerpt",
    imgPath:
      "https://images.nappy.co/uploads/large/21592178174kqah8td9ipie9jypo1keymszjbhqpzk0riykxxiwbcjmt6z895otlvsxe00ymauvqdxie4admvrkzwkbidhouo8xihixud4zjink.jpg?auto=format&fm=jpg&w=1280&q=75",
    altText: "hand holding a megaphone",
    slug: "test-post5",
  },
  {
    title: "Post title",
    date: Date.now(),
    excerpt: "The post excerpt",
    imgPath:
      "https://images.nappy.co/uploads/large/21592178174kqah8td9ipie9jypo1keymszjbhqpzk0riykxxiwbcjmt6z895otlvsxe00ymauvqdxie4admvrkzwkbidhouo8xihixud4zjink.jpg?auto=format&fm=jpg&w=1280&q=75",
    altText: "hand holding a megaphone",
    slug: "test-post6",
  },
  {
    title: "Post title",
    date: Date.now(),
    excerpt: "The post excerpt",
    imgPath:
      "https://images.nappy.co/uploads/large/21592178174kqah8td9ipie9jypo1keymszjbhqpzk0riykxxiwbcjmt6z895otlvsxe00ymauvqdxie4admvrkzwkbidhouo8xihixud4zjink.jpg?auto=format&fm=jpg&w=1280&q=75",
    altText: "hand holding a megaphone",
    slug: "test-post7",
  },
  {
    title: "Post title",
    date: Date.now(),
    excerpt: "The post excerpt",
    imgPath:
      "https://images.nappy.co/uploads/large/21592178174kqah8td9ipie9jypo1keymszjbhqpzk0riykxxiwbcjmt6z895otlvsxe00ymauvqdxie4admvrkzwkbidhouo8xihixud4zjink.jpg?auto=format&fm=jpg&w=1280&q=75",
    altText: "hand holding a megaphone",
    slug: "test-post8",
  },
  {
    title: "Post title",
    date: Date.now(),
    excerpt: "The post excerpt",
    imgPath:
      "https://images.nappy.co/uploads/large/21592178174kqah8td9ipie9jypo1keymszjbhqpzk0riykxxiwbcjmt6z895otlvsxe00ymauvqdxie4admvrkzwkbidhouo8xihixud4zjink.jpg?auto=format&fm=jpg&w=1280&q=75",
    altText: "hand holding a megaphone",
    slug: "test-post9",
  },
];
export const DUMMY_POST = {
  title: "Post title",
  date: Date.now(),
  imgPath:
    "https://images.nappy.co/uploads/large/21592178174kqah8td9ipie9jypo1keymszjbhqpzk0riykxxiwbcjmt6z895otlvsxe00ymauvqdxie4admvrkzwkbidhouo8xihixud4zjink.jpg?auto=format&fm=jpg&w=1280&q=75",
  altText: "hand holding a megaphone",
  slug: "test-post9",
  content:
    "# This a test post, you really are quite lucky to be reading this. That means that I trust you to see my 'work in progress'. Who knows what I will actually write, but I bet it will have words and punctuation!",
};
